apiVersion: v2
appVersion: 2.26.1
dependencies:
- name: libcoder
  repository: file://../libcoder
  version: 0.1.0
description: External provisioner daemon for Coder. This is an Enterprise feature;
  contact sales@coder.com.
home: https://github.com/coder/coder
icon: https://helm.coder.com/coder_logo_black.png
keywords:
- coder
- terraform
kubeVersion: '>= 1.19.0-0'
maintainers:
- email: support@coder.com
  name: Coder Technologies, Inc.
  url: https://coder.com/contact
name: coder-provisioner
sources:
- https://github.com/coder/coder/tree/main/helm/provisioner
type: application
version: 2.26.1
